### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by pablo384** [leonlovett/angular2-universal-material-firebase#1]
When I deploy the app it render but not ssr. in other hand the server render is this below.

`   <!DOCTYPE html>
   <html lang="en">
  <head>
  <meta charset="utf-8">
  <title>Error</title>
  </head>
  <body>
  <pre>Internal Server Error</pre>
  </body>
  </html>`

**Comment by leonlovett** [comment]
Is this deployed to Firebase? If so, can you provide a url? I will take a look and see if I can determine what is going on.

**Comment by pablo384** [comment]
https://angular-started.firebaseapp.com

Yes, it's in Firebase.

**Comment by leonlovett** [comment]
I'm not sure what's going on here. Can you post the contents of your server.ts file?

**Comment by pablo384** [comment]
https://github.com/pablo384/angular-ssr-prueba
the project is here.
the content of server.ts is this:

`require('zone.js/dist/zone-node');
const renderModuleFactory = require('@angular/platform-server').renderModuleFactory;
const AppServerModuleNgFactory = require('../dist-server/main.635f26724716e2069f2e.bundle.js').AppServerModuleNgFactory; // bundle name set by npm script build-set-server-main-bundle
const path = require('path');
// const index = require('fs').readFileSync(path.join(__dirname, '..', '/dist-server/index.html'), 'utf8'); // for server side rendering
const index = require('fs').readFileSync(path.join(__dirname, '..', 'dist/index.html'), 'utf8'); // for server to client transition
const express = require('express');

const app = express();
const port = process.env.port || 3000;

app.use(express.static(path.join(__dirname, '..', 'dist'), {
    index: false
}));

app.use('*', function (req, res, next) {
    // res.sendFile(path.join(__dirname,'../dist/index.html'));
    renderModuleFactory(
        AppServerModuleNgFactory, { document: index, url: req.baseUrl }).then(html => {
            res.send(html);
        });
});

app.listen(port, function () {
    console.log('listening on port: ' + port);
});`

**Comment by leonlovett** [comment]
I'll look at this further this evening. In the meantime, if you haven't already, you can check the functions log within Firebase to see if there are any errors being logged.

![image](https://user-images.githubusercontent.com/8462457/31832893-3b632df2-b58e-11e7-91a3-a38bbbcd1479.png)

**Comment by pablo384** [comment]
![screenshot from 2017-10-20 21-46-40](https://user-images.githubusercontent.com/22134437/31846927-901fb8d6-b5e0-11e7-9b4e-bdddbbc1d8ba.png)


I'm checking the error. I updated the dependence but with the same result.

**Comment by leonlovett** [comment]
Sorry for the delayed response. Did you ever get this sorted?

**Comment by pablo384** [comment]
Yes I got it, but with the example universal started in a static folder. I couldn't find other way.
